USE timeline;

DROP TABLE IF EXISTS IMG;
DROP TABLE IF EXISTS HUMOR_COMMENT;
DROP TABLE IF EXISTS HUMOR_BOARD;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    USER_ID      INT   NOT NULL AUTO_INCREMENT,
    ID         VARCHAR(60)   NOT NULL,
    NICKNAME   VARCHAR(24)   NOT NULL,
    PW         VARCHAR(64)   NOT NULL,
    GENDER      VARCHAR(2)   NOT NULL,
    BIRTHDAY   VARCHAR(8)   NULL,
    AGREE_CODE      INT   NOT NULL,
    SNS_TYPE      VARCHAR(10)   NULL,
    JOIN_DATE      DATE   NOT NULL,
    PW_MODIFY_DATE       DATE NULL,
    SESSION_ID         VARCHAR(32)   NULL,
    SESSION_LIMIT_DATE   DATE   NULL,
    BANNED_STATE       INT NOT NULL,
    PRIMARY KEY(USER_ID)
);

CREATE TABLE HUMOR_BOARD (
    HUMOR_ID INT NOT NULL  AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL,
    CONTENT TEXT(20000) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    HIT INT NOT NULL,
    USER_ID INT,
    STATE INT NOT NULL,
    IP VARCHAR(30) NULL,
    MODIFY_DATE DATE NULL,
    PRIMARY KEY (HUMOR_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL
);


CREATE TABLE HUMOR_COMMENT (
    HUMOR_CO_ID INT NOT NULL AUTO_INCREMENT,
    HUMOR_ID INT,
    CO_CONTENT VARCHAR(1000) NOT NULL,
    CO_CREATE_DATE DATE NOT NULL,
    STATE INT NOT NULL,
    DEPTH INT NOT NULL,
    GROUP_NO INT NOT NULL,
    GROUP_ORDER INT NOT NULL,
    USER_ID INT,
    PRIMARY KEY (HUMOR_CO_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL,
    FOREIGN KEY (HUMOR_ID) REFERENCES HUMOR_BOARD(HUMOR_ID) ON DELETE CASCADE
);

CREATE TABLE IMG (
    IMG_ID INT NOT NULL AUTO_INCREMENT,
    FILESYSTEM  VARCHAR(42),
    HUMOR_ID INT,
    PRIMARY KEY(IMG_ID),
    FOREIGN KEY(HUMOR_ID) REFERENCES HUMOR_BOARD(HUMOR_ID) ON DELETE CASCADE
);