spring:
  application:
  name: timeline
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  web:
    resources:
      static-locations: /resources/**
  # database active mode (dev, prod)
  profiles:
      active: dev

# mybatis
mybatis:
  config-location: mybatis/config/mybatis-config.xml
  mapper-locations: mybatis/mapper/*.xml

# captcha
api:
  client_id: E4GVk9DUr941MwQkCkN3
  client_secret: gj52u3dQ2n
