DROP TABLE IF EXISTS TMP_IMG;
DROP TABLE IF EXISTS TMP_HUMOR_BOARD;
DROP TABLE IF EXISTS IMG;
DROP TABLE IF EXISTS HUMOR_COMMENT;
DROP TABLE IF EXISTS HUMOR_BOARD;
DROP TABLE IF EXISTS USERS;

-- 회원
CREATE TABLE USERS (
    USER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID VARCHAR(60) NOT NULL,
    NICKNAME VARCHAR(24) NOT NULL,
    PW VARCHAR(64) NOT NULL,
    GENDER VARCHAR(2) NOT NULL,
    BIRTHDAY VARCHAR(8),
    AGREE_CODE INT NOT NULL,
    SNS_TYPE VARCHAR(10),
    JOIN_DATE DATE NOT NULL,
    PW_MODIFY_DATE DATE,
    SESSION_ID VARCHAR(32),
    SESSION_LIMIT_DATE DATE,
    BANNED_STATE INT NOT NULL
);

-- 유머게시판
CREATE TABLE HUMOR_BOARD (
     HUMOR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     TITLE VARCHAR(100) NOT NULL,
     CONTENT TEXT NOT NULL,
     CREATE_DATE DATE NOT NULL,
     HIT INT NOT NULL,
     USER_ID INT,
     STATE INT NOT NULL,
     IP VARCHAR(30),
     MODIFY_DATE DATE,
     FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 유머게시판 댓글
CREATE TABLE HUMOR_COMMENT (
    HUMOR_CO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    HUMOR_ID INT,
    CO_CONTENT VARCHAR(1000) NOT NULL,
    CO_CREATE_DATE DATE NOT NULL,
    STATE INT NOT NULL,
    DEPTH INT NOT NULL,
    GROUP_NO INT NOT NULL,
    GROUP_ORDER INT NOT NULL,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID),
    FOREIGN KEY (HUMOR_ID) REFERENCES HUMOR_BOARD(HUMOR_ID) ON DELETE CASCADE
);

-- 유머게시판 이미지
CREATE TABLE IMG (
     IMG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     FILESYSTEM VARCHAR(42),
     HUMOR_ID INT,
     FOREIGN KEY (HUMOR_ID) REFERENCES HUMOR_BOARD(HUMOR_ID) ON DELETE CASCADE
);

-- 유머게시판 임시저장
CREATE TABLE TMP_HUMOR_BOARD (
     TMP_HUMOR_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     TITLE VARCHAR(100) NOT NULL,
     CONTENT TEXT NOT NULL,
     SAVE_DATE DATE NOT NULL,
     USER_ID INT,
     FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

-- 유머게시판 이미지 임시저장
CREATE TABLE TMP_IMG (
     TMP_IMG_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
     FILESYSTEM VARCHAR(42),
     TMP_HUMOR_ID INT,
     FOREIGN KEY (TMP_HUMOR_ID) REFERENCES TMP_HUMOR_BOARD(TMP_HUMOR_ID) ON DELETE CASCADE
);